# Generated by Django 5.1.4 on 2024-12-09 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Property Name')),
                ('location', models.CharField(max_length=255, verbose_name='Property Location')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Property Price')),
                ('type', models.CharField(choices=[('Residential', 'Residential'), ('Commercial', 'Commercial')], max_length=20, verbose_name='Property Type')),
                ('status', models.CharField(choices=[('Available', 'Available'), ('Sold', 'Sold')], max_length=10, verbose_name='Status')),
            ],
        ),
    ]
